version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: invoice_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    volumes:
      - mongo_data:/data/repositories

volumes:
  mongo_data:
